src/main/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSession.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/ThriftFrameDecoder.java
src/test/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSessionTest.java

Sometimes we may need to abandon a message to emulate the replica session timeout in test. In the old implementation, it's handled by sending an invalid RPC code to server and relying on pegasus-server to ignore the request. 
However, the server has changed its implementation which doesn't ignore unrecognized RPC codes any more. So we'd better abandon a response on the client side.

rpc: add message filter to support abandon message easily

---

src/main/java/com/xiaomi/infra/pegasus/client/PegasusCli.java

and support Compress/Uncompress when copying data.

add copy_data operator in PegasusCli

---

src/main/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSession.java

fix #25 
Tested with ycsb threadcount=1/10/20:
1. Set up a docker onebox and run ycsb.
```
>>> nodes -d
address               status              replica_count       primary_count       secondary_count     
172.21.0.21:34801     ALIVE               4                   1                   3                   
172.21.0.22:34801     ALIVE               5                   2                   3                   
172.21.0.23:34801     ALIVE               5                   2                   3                   
172.21.0.24:34801     ALIVE               5                   1                   4                   
172.21.0.25:34801     ALIVE               5                   2                   3                   
total_node_count   : 5
alive_node_count   : 5
unalive_node_count : 0
```
2. …

close session when it's not responding for a while

---

src/main/java/com/xiaomi/infra/pegasus/client/ClientOptions.java
src/main/java/com/xiaomi/infra/pegasus/client/PegasusClientFactory.java
src/test/java/com/xiaomi/infra/pegasus/client/TestBasic.java

添加了createClient(clientOptions) 、getSingletonClient(clientOptions)接口，使得用户可以直接传入配置参数（而不用写配置文件）就可以创建client
该功能为小米大数据临时需求。

add createClient API with clientOptions

---

.travis.yml
pom.xml
scripts/format-all.sh
scripts/travis.sh
src/main/java/com/xiaomi/infra/pegasus/tools/FlowController.java

Our user reported that 1.11.5-thrift-0.11.0-inlined occasionally hangs the thread forever, see this stack:
It seems to be the bug of netty-4.0.33 according to https://github.com/netty/netty/issues/6815.
This PR doesn't totally eliminate the potential risk of netty's bug, since our user may still depend on a lower version of netty that hides ours. A better solution is to use maven's shade plugin. I'll consider it when netty-4.0.56 cannot work.

upgrade netty version to 4.0.56.Final

---

.travis.yml
pom.xml
src/main/java/com/xiaomi/infra/pegasus/client/FutureGroup.java
src/main/java/com/xiaomi/infra/pegasus/client/PegasusTable.java
src/test/java/com/xiaomi/infra/pegasus/client/TestFutureGroup.java

The user's bug of https://github.com/XiaoMi/pegasus-java-client/pull/50 still remains and it seems not a netty's bug.
I suspect it was due to some sort of deadlock or broken RPC that makes `Future.awaitUninterruptibly` waiting.
The bug is unknown, but some improvements may still help:
- Rethrow `BlockingOperationException` (a try/catch block wraps around `future.await`) if user thread is in the same eventloop with netty. This is hardly a possible situation but may increase our robustness.
- Use `await(timeoutMillis)` instead of `awaitUninterruptibly` to prevent the case we are unknown where the user's RPC is always incomplete but timeout is expired.

bugfix: catch and rethrow BlockingOperationException for batchSet

---

carrot
pom.xml
src/main/java/com/xiaomi/infra/pegasus/client/FutureGroup.java
src/test/java/com/xiaomi/infra/pegasus/client/TestFutureGroup.java

`waitAllCompleteOrOneFail` will throw `NullPointException` when timeout expired in current implementation. Because `Future.cause()` could be null when the result is not available in time.
This SNAPSHOT version was deployed on one of our users' environment (c3srv-xiaoai/ai_profile_data).

fix: handle case where Future.cause() is null in FutureGroup

---

src/main/java/com/xiaomi/infra/pegasus/client/PegasusTable.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java

原有的异常信息仅给出错误码，例如ERR_OBJECT_NOT_FOUND，而没有详细的异常信息，这种错误：
1、用户不能明白具体含义
2、不利于问题追踪
该PR在抛异常处重新添加了处理异常的逻辑，细化各个错误码的具体描述，并给出必要的信息，修改过后的异常信息将类似：
```
ERR_OBJECT_NOT_FOUND: [metaServer=[127.0.0.1:34601, 127.0.0.1:34602, 127.0.0.1:34603],tableName=temps] No such table. Please make sure your meta addresses and table name are correct!!
```
```
ERR_TIMEOUT: [table=temp,operation=get,replicaServer=0.0.0.0:0,gPid=(gpid(1.4))] The operationTimeout is 1000ms!
````

refactor: add more exception info

---

pom.xml
scripts/format-all.sh
src/main/java/com/xiaomi/infra/pegasus/base/rpc_address.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/HostNameResolver.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/MetaSession.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSession.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java
src/test/java/com/xiaomi/infra/pegasus/base/TestRpcAddress.java
src/test/java/com/xiaomi/infra/pegasus/rpc/async/MetaSessionTest.java

该PR核心代码来源：[pull#41](https://github.com/XiaoMi/pegasus-java-client/pull/41)
该PR提供对meta域名的解析，并兼容之前的url list格式。新增的域名支持格式如下：
```
tjwqtst-staging.pegasus.hadoop.srv:34601
```
该PR新增和修改的主要地方如下：
1、添加了`HostNameResolver`用于解析host
2、在`MetaSession`初始化过程添加了meta地址格式判断，以兼容url list格式
3、在`onFinishQueryMeta`中，增加了dns自动刷新逻辑：meta url为host格式下，当metalist中所有的地址失效后，强制刷新DNS
4、在`MetaRequestRound`中添加`maxResolveCount`，以支持在DNS刷新之后依然失败的情况，启动有限次的重试
注意：DNS解析依赖DNS域名系统支持，需在域名系统中注册不同集群对应的域名，并在后续变更中手动维护

feat: support resolving meta host through DNS

---

src/main/java/com/xiaomi/infra/pegasus/base/error_code.java
src/main/java/com/xiaomi/infra/pegasus/client/PException.java
src/main/java/com/xiaomi/infra/pegasus/client/PegasusTable.java
src/test/java/com/xiaomi/infra/pegasus/client/TestPException.java

In most synchronous APIs of PegasusTable, when `Future.await` throws `InterruptedException` and `TimeoutException`, they are wrapped under PException with simply coded ERR_TIMEOUT. This makes it hard to distinguish the real problem.
So here we add more details on each exception, InterruptedException is coded ERR_THREAD_INTERRUPTED, and information like "tableName" and "timeout ms" is complemented.

feat: add more exception info on synchronous APIs

---

.arcconfig
pom.xml
src/main/java/com/xiaomi/infra/pegasus/client/FutureGroup.java
src/main/java/com/xiaomi/infra/pegasus/client/PException.java
src/main/java/com/xiaomi/infra/pegasus/client/PegasusTable.java
src/test/java/com/xiaomi/infra/pegasus/client/TestPException.java

Package version is necessary for debugging our clients in Xiaomi, where hundreds of users are using pegasus-java-client in different versions. Some may misuse but insist they are using the latest version (usually with less bugs). With version included in `PException`, we can save time for digging down to the root cause.
We use **maven-jar-plugin** to inject the version during packaging. To obtain the version we use
```java
PException.class.getPackage().getImplementationVersion()
```
When unit test the version is set "{version}" as a place-holder.
Finally the exception message of a PException is like:
```
com.xiaomi.infra.pegasus.client.PException: 1.11.8-thrift-0.11.0-inlined: com.xiaomi.infra.pegasus.rpc.ReplicationException: ERR_OBJECT_NOT_FOUND: …
```

feat: have package version prefixed in PException

---

pom.xml
src/main/java/com/xiaomi/infra/pegasus/rpc/async/HostNameResolver.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/MetaSession.java

DNS域名功能为了检测域名地址格式的有效性，使用了Apache 的`commons-validator` 包的 `InetAddressValidator.getInstance().isValid` 方法，其中`InetAddressValidator.getInstance()`在某些机器上可能会引起阻塞。目前并未发现引起阻塞的原因，该PR更换成了Guava包，该bug并未出现。

fix: fix block bug of InetAddressValidator.getInstance()

---

src/main/java/com/xiaomi/infra/pegasus/rpc/Cluster.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/ClusterManager.java

use operation_timeout as socket connect timeout, instead of Cluster.SOCK_TIMEOUT.
This fixes the problem that the client may request a disconnected replica-server when the session was unable to establish in `SOCKET_TIMEOUT` (aka 1 second), and finally gets `ERR_SESSION_RESET` error, even though its `operationTimeout` is 10 seconds.
This is user-unfriendly and counterintuitive because the user actually allows 10 seconds to wait, but the request didn't utilize the sufficient time budget.

fix: use operation_timeout as socket connect timeout

---

src/main/java/com/xiaomi/infra/pegasus/client/PegasusTable.java
src/main/java/com/xiaomi/infra/pegasus/rpc/Cluster.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/ClusterManager.java
src/test/java/com/xiaomi/infra/pegasus/client/TestPException.java

If user set operation timeout to a very small value, for example 1ms, it is abviously not enought to establish a socket connect. so we bound a minimal value of 1000ms for socket connect timeout.

refactor: bound minimal value for socket connect timeout

---

src/main/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSession.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/ThriftFrameDecoder.java
src/test/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSessionTest.java

```
[WARN  2019-12-04 21:00:08.478] [nioEventLoopGroup-3-1] com.xiaomi.infra.pegasus.rpc.async.ReplicaSession$DefaultHandler.exceptionCaught(ReplicaSession.java:332) [got exception in inbound handler [id: 0x37bcb165, L:/10.132.63.11:42530 ! R:/10.142.98.29:34801] for session rpc_address(10.142.98.29:34801): ]
java.lang.NullPointerException
at com.xiaomi.infra.pegasus.rpc.async.ReplicaSession.tryNotifyWithSequenceID(ReplicaSession.java:237)
at com.xiaomi.infra.pegasus.rpc.async.ReplicaSession.markSessionDisconnect(ReplicaSession.java:214)
at com.xiaomi.infra.pegasus.rpc.async.ReplicaSession.access$200(ReplicaSession.java:25)
at com.xiaomi.infra.pegasus.rpc.async.ReplicaSession$DefaultHandler.channelInactive(ReplicaSession.java:310)
at …
```

fix: handle potential NullPointerException on RequestEntry.timeoutTask

---

src/main/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSession.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java
src/test/java/com/xiaomi/infra/pegasus/rpc/async/MetaSessionTest.java
src/test/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSessionTest.java
src/test/java/com/xiaomi/infra/pegasus/rpc/async/TableHandlerTest.java

In addition to being able to close a session when it's still connecting, in this PR we also make connection warmup (connect before sending RPC) only runs when the session is disconnected.
To close the session when it's still connecting, we modified `ReplicaSession#closeSession` and call `markSessionDisconnect` after identifying that it's CONNECTING. This is intended to fix the bug #80.
To make connection warmup only runs when the session is disconnected, we wrapped `doConnect` as `tryConnect`, which checks if the session is disconnected. If not, it will do nothing.

fix: close session when unable to connect

---

src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java

There is no need to let client know whether the primary/ballot in a replica group is changed or not. So deleted the unused log.

refactor: delete unused log in TableHandler

---

src/main/java/com/xiaomi/infra/pegasus/client/SetItem.java

Writing to Pegasus on Spark usually need to use batchSet API as well as `SetItem` for batching the writes.
But if we store `SetItem` in an RDD, there's a problem that `RDD[SetItem]` can not be serialized by Spark. Some exceptions will be thrown at runtime due to this cause. So here we make SetItem Serializable.

fix: make SetItem Serializable

---

src/main/java/com/xiaomi/infra/pegasus/rpc/async/ClientRequestRound.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java

The #93 pr create new `ClientRequestRound` object when excute `tryDelayCall`:
https://github.com/XiaoMi/pegasus-java-client/blob/76620abd0d763af126f570b0cfc84296887bd966/src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java#L326-L329
it's `expireNanoTime` will be reset `currentTime+timeout`:
https://github.com/XiaoMi/pegasus-java-client/blob/76620abd0d763af126f570b0cfc84296887bd966/src/main/java/com/xiaomi/infra/pegasus/rpc/async/ClientRequestRound.java#L42-L43
then the https://github.com/XiaoMi/pegasus-java-client/blob/76620abd0d763af126f570b0cfc84296887bd966/src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java#L334
will be always true. In this case, the reuqest will not stop retry until it is successful.
This pr add new constructor to support use origin …

fix: use origin expireNanoTime to init new clientRequestRound

---

pom.xml
src/main/java/com/xiaomi/infra/pegasus/client/DelRangeOptions.java
src/main/java/com/xiaomi/infra/pegasus/client/PegasusTable.java
src/test/java/com/xiaomi/infra/pegasus/client/TestBasic.java

`startSortKey` should support pass `null` 
```java
public void delRange(
byte[] hashKey, byte[] startSortKey, byte[] stopSortKey, DelRangeOptions options, int timeout)
throws PException {
ScanOptions scanOptions = new ScanOptions();
scanOptions.noValue = true;
scanOptions.startInclusive = options.startInclusive;
scanOptions.stopInclusive = options.stopInclusive;
scanOptions.sortKeyFilterType = options.sortKeyFilterType;
scanOptions.sortKeyFilterPattern = options.sortKeyFilterPattern;
options.nextSortKey = new String(startSortKey);
```
```java
public class DelRangeOptions {
public String nextSortKey = "";
```
Because DelRangeOptions.nextSortKey was a string, if startSortKey was passed null, `new String(null)` will throw NullPointerException.
**Besides**, this pr update junit4 to junit5 for …

fix: startSortKey can't  pass null

---

src/main/java/com/xiaomi/infra/pegasus/client/PConfigUtil.java

fix: release streams resource while loading config

---

src/main/java/com/xiaomi/infra/pegasus/client/ClientOptions.java
src/main/java/com/xiaomi/infra/pegasus/rpc/ClusterOptions.java

#76 set the `asyncWorkers = Runtime.getRuntime().availableProcessors()`, however it is useless, this pr revert it to `4`

fix: revert default asyncWorkers value

---

scripts/travis.sh
src/main/java/com/xiaomi/infra/pegasus/operator/client_operator.java
src/main/java/com/xiaomi/infra/pegasus/operator/read_operator.java
src/main/java/com/xiaomi/infra/pegasus/operator/rrdb_get_operator.java
src/main/java/com/xiaomi/infra/pegasus/operator/rrdb_multi_get_operator.java
src/main/java/com/xiaomi/infra/pegasus/operator/rrdb_ttl_operator.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java
src/test/java/com/xiaomi/infra/pegasus/operator/ClientOperatorTest.java

`client_operator#enableBackupRequest` was ambigious with user configuration `TableHandler#isBackupRequestEnabled`.
`client_operator#enableBackupRequest` is actually not given by users. The word "enable" is not accurate. I'd like to use "support" instead. Because only reads support backup-request.

refactor: restrict enableBackupRequest to read_operator

---

src/main/java/com/xiaomi/infra/pegasus/client/ClientOptions.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/ClusterManager.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/Negotiation.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSession.java
src/main/java/com/xiaomi/infra/pegasus/rpc/async/TableHandler.java
src/main/java/com/xiaomi/infra/pegasus/rpc/interceptor/InterceptorManager.java
src/test/java/com/xiaomi/infra/pegasus/rpc/async/ReplicaSessionTest.java

1. add a configuration of `enable_auth`
2. add negotiation class
3. rename `InterceptorManger` to `InterceptorManager`

feat(security): add negotiation class

---

idl/apache-licence-template
src/main/java/com/xiaomi/infra/pegasus/security/KerberosProtocol.java

If we use kerberos in jaas, we should refresh tgt in background to keep the authentication succeed.
For more details: https://levy5307.github.io/blog/jaas-tgt-renewal/
So in this pull request, I add a background thread to check and refresh the tgt periodically.
Print the life time of tgt obtain in java client. And we can see the life time of this tgt is updated before it is expired(At line 8).
1. the remain lifetime of tgt: 69 seconds
2. the remain lifetime of tgt: 59 seconds
3. the remain lifetime of tgt: 49 seconds
4. the remain lifetime of tgt: 39 seconds
5. the remain lifetime of tgt: 29 seconds
6. the remain lifetime of tgt: 19 seconds
7. ***the remain lifetime of tgt: 9 seconds***
8. ***the remain lifetime of tgt: 69 seconds***
9. the remain lifetime of tgt: 59 seconds
10. the …

feat(security): refresh tgt in background

---

src/main/java/com/xiaomi/infra/pegasus/rpc/async/ClientRequestRound.java

timeoutInMilliseconds should be transform to nano seconds

fix: incorrect expire time of client request 
